name: kristyswanson
favicon: null
layout_spectrum: 0.3634207157883793
typography_spectrum: 0.6798080790322274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7914124231319875
  lightness: 0.35174828371964395
  saturation: 0.19100753590464592
  rhythmicContrast: 0.7233342844992876
purpose: []
